name: Deploy to Firebase Hosting on PR
'on': pull_request
jobs:
  build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      
      - name: Install Pug CLI
        run: npm install -g pug-cli
      
      - name: Install SASS CLI
        run: npm install -g sass
      
      - name: Install JS-YAML CLI
        run: npm install -g js-yaml
      
      - name: Render the website from templates
        run: |
          chmod +x ./render.sh
          ./render.sh
      - name: Firebase Deploy to Preview Channel
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_HARYANDI1796 }}'
          projectId: fake-videocall
